#ifndef UE4SS_SDK_A_Man_Riding_AnimBP_HPP
#define UE4SS_SDK_A_Man_Riding_AnimBP_HPP

struct FAnimBlueprintGeneratedConstantData : public FAnimBlueprintConstantData
{
    FName __NameProperty_815;                                                         // 0x0004 (size: 0x8)
    FName __NameProperty_816;                                                         // 0x000C (size: 0x8)
    FName __NameProperty_817;                                                         // 0x0014 (size: 0x8)
    FName __NameProperty_818;                                                         // 0x001C (size: 0x8)
    FName __NameProperty_819;                                                         // 0x0024 (size: 0x8)
    FName __NameProperty_820;                                                         // 0x002C (size: 0x8)
    FName __NameProperty_821;                                                         // 0x0034 (size: 0x8)
    FName __NameProperty_822;                                                         // 0x003C (size: 0x8)
    FName __NameProperty_823;                                                         // 0x0044 (size: 0x8)
    FName __NameProperty_824;                                                         // 0x004C (size: 0x8)
    FName __NameProperty_825;                                                         // 0x0054 (size: 0x8)
    FName __NameProperty_826;                                                         // 0x005C (size: 0x8)
    EAnimSyncMethod __EnumProperty_827;                                               // 0x0064 (size: 0x1)
    FName __NameProperty_828;                                                         // 0x0068 (size: 0x8)
    FName __NameProperty_829;                                                         // 0x0070 (size: 0x8)
    FName __NameProperty_830;                                                         // 0x0078 (size: 0x8)
    int32 __IntProperty_831;                                                          // 0x0080 (size: 0x4)
    FName __NameProperty_832;                                                         // 0x0084 (size: 0x8)
    int32 __IntProperty_833;                                                          // 0x008C (size: 0x4)
    FName __NameProperty_834;                                                         // 0x0090 (size: 0x8)
    int32 __IntProperty_835;                                                          // 0x0098 (size: 0x4)
    FName __NameProperty_836;                                                         // 0x009C (size: 0x8)
    int32 __IntProperty_837;                                                          // 0x00A4 (size: 0x4)
    TEnumAsByte<ESequenceEvalReinit::Type> __ByteProperty_838;                        // 0x00A8 (size: 0x1)
    bool __BoolProperty_839;                                                          // 0x00A9 (size: 0x1)
    class UAnimSequenceBase* __AnimSequenceBase_840;                                  // 0x00B0 (size: 0x8)
    EAlphaBlendOption __EnumProperty_841;                                             // 0x00B8 (size: 0x1)
    TArray<float> __ArrayProperty_842;                                                // 0x00C0 (size: 0x10)
    FName __NameProperty_843;                                                         // 0x00D0 (size: 0x8)
    float __FloatProperty_844;                                                        // 0x00D8 (size: 0x4)
    float __FloatProperty_845;                                                        // 0x00DC (size: 0x4)
    float __FloatProperty_846;                                                        // 0x00E0 (size: 0x4)
    class UBlendProfile* __BlendProfile_847;                                          // 0x00E8 (size: 0x8)
    class UCurveFloat* __CurveFloat_848;                                              // 0x00F0 (size: 0x8)
    EAlphaBlendOption __EnumProperty_849;                                             // 0x00F8 (size: 0x1)
    EBlendListTransitionType __EnumProperty_850;                                      // 0x00F9 (size: 0x1)
    TArray<float> __ArrayProperty_851;                                                // 0x0100 (size: 0x10)
    TArray<int32> __ArrayProperty_852;                                                // 0x0110 (size: 0x10)
    FName __NameProperty_853;                                                         // 0x0120 (size: 0x8)
    FName __NameProperty_854;                                                         // 0x0128 (size: 0x8)
    FName __NameProperty_855;                                                         // 0x0130 (size: 0x8)
    FName __NameProperty_856;                                                         // 0x0138 (size: 0x8)
    int32 __IntProperty_857;                                                          // 0x0140 (size: 0x4)
    FName __NameProperty_858;                                                         // 0x0144 (size: 0x8)
    int32 __IntProperty_859;                                                          // 0x014C (size: 0x4)
    FName __NameProperty_860;                                                         // 0x0150 (size: 0x8)
    FName __NameProperty_861;                                                         // 0x0158 (size: 0x8)
    FName __NameProperty_862;                                                         // 0x0160 (size: 0x8)
    int32 __IntProperty_863;                                                          // 0x0168 (size: 0x4)
    float __FloatProperty_864;                                                        // 0x016C (size: 0x4)
    FInputScaleBiasClampConstants __StructProperty_865;                               // 0x0170 (size: 0x2C)
    float __FloatProperty_866;                                                        // 0x019C (size: 0x4)
    bool __BoolProperty_867;                                                          // 0x01A0 (size: 0x1)
    EAnimSyncMethod __EnumProperty_868;                                               // 0x01A1 (size: 0x1)
    TEnumAsByte<EAnimGroupRole::Type> __ByteProperty_869;                             // 0x01A2 (size: 0x1)
    FName __NameProperty_870;                                                         // 0x01A4 (size: 0x8)
    FName __NameProperty_871;                                                         // 0x01AC (size: 0x8)
    FName __NameProperty_872;                                                         // 0x01B4 (size: 0x8)
    int32 __IntProperty_873;                                                          // 0x01BC (size: 0x4)
    FAnimNodeFunctionRef __StructProperty_874;                                        // 0x01C0 (size: 0x20)
    FAnimSubsystem_PropertyAccess AnimBlueprintExtension_PropertyAccess;              // 0x01E0 (size: 0x80)
    FAnimSubsystem_Base AnimBlueprintExtension_Base;                                  // 0x0260 (size: 0x18)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_10;     // 0x0278 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_7;                 // 0x02A8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_6;                 // 0x02D8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedAnimLayer;        // 0x0308 (size: 0x30)
    FAnimNodeExposedValueHandler AnimGraphNode_LinkedInputPose_9;                     // 0x0338 (size: 0x8)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_8;      // 0x0340 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_7;      // 0x0370 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_6;       // 0x03A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_5;                 // 0x03D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_6;      // 0x0400 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_4;                 // 0x0430 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_5;      // 0x0460 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_3;                 // 0x0490 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_5;       // 0x04C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_4;      // 0x04F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_3;      // 0x0520 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_2;     // 0x0550 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_21;         // 0x0580 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_7;         // 0x05B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_2;      // 0x05E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_2;                 // 0x0610 (size: 0x30)
    FAnimNodeExposedValueHandler AnimGraphNode_LinkedInputPose_1;                     // 0x0640 (size: 0x8)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_1;                 // 0x0648 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_4;       // 0x0678 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_17;      // 0x06A8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                   // 0x06D8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_41;    // 0x0708 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_40;    // 0x0738 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_39;    // 0x0768 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_38;    // 0x0798 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_37;    // 0x07C8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_15;       // 0x07F8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_20;         // 0x0828 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_14;       // 0x0858 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_19;         // 0x0888 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_16;      // 0x08B8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_18;         // 0x08E8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_6;         // 0x0918 (size: 0x30)
    FAnimNodeExposedValueHandler AnimGraphNode_LinkedInputPose;                       // 0x0948 (size: 0x8)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_36;    // 0x0950 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_13;       // 0x0980 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_17;         // 0x09B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_16;         // 0x09E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_5;         // 0x0A10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                   // 0x0A40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_1;     // 0x0A70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_7;        // 0x0AA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer;       // 0x0AD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_15;         // 0x0B00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_4;         // 0x0B30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_3;       // 0x0B60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_35;    // 0x0B90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_34;    // 0x0BC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_33;    // 0x0BF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_32;    // 0x0C20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_31;    // 0x0C50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_30;    // 0x0C80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_29;    // 0x0CB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_28;    // 0x0CE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_27;    // 0x0D10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_26;    // 0x0D40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_25;    // 0x0D70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_24;    // 0x0DA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_23;    // 0x0DD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_22;    // 0x0E00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_21;    // 0x0E30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_20;    // 0x0E60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_19;    // 0x0E90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_18;    // 0x0EC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_17;    // 0x0EF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_16;    // 0x0F20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_15;    // 0x0F50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_14;    // 0x0F80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_13;    // 0x0FB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_15;      // 0x0FE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_6;        // 0x1010 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_12;       // 0x1040 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_14;         // 0x1070 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_14;      // 0x10A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_5;        // 0x10D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_11;       // 0x1100 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_13;         // 0x1130 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_12;    // 0x1160 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_13;      // 0x1190 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_4;        // 0x11C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_10;       // 0x11F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_12;         // 0x1220 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;      // 0x1250 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;      // 0x1280 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;      // 0x12B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_1;      // 0x12E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum_2;      // 0x1310 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;       // 0x1340 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_3;        // 0x1370 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_9;        // 0x13A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_11;         // 0x13D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;    // 0x1400 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;    // 0x1430 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;       // 0x1460 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;       // 0x1490 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;       // 0x14C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequenceEvaluator;      // 0x14F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_8;        // 0x1520 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_2;        // 0x1550 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;        // 0x1580 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum_1;      // 0x15B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_10;         // 0x15E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;       // 0x1610 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;       // 0x1640 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;       // 0x1670 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;       // 0x16A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TwoWayBlend;            // 0x16D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive_1;        // 0x1700 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum;        // 0x1730 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_7;        // 0x1760 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_9;          // 0x1790 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_3;         // 0x17C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_8;          // 0x17F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;     // 0x1820 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_6;        // 0x1850 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_7;          // 0x1880 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_5;        // 0x18B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_6;          // 0x18E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_2;         // 0x1910 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_2;       // 0x1940 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;     // 0x1970 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;     // 0x19A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;     // 0x19D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;     // 0x1A00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;     // 0x1A30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;     // 0x1A60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;     // 0x1A90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;       // 0x1AC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive;          // 0x1AF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_4;        // 0x1B20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_5;          // 0x1B50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_3;        // 0x1B80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;          // 0x1BB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_2;        // 0x1BE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;          // 0x1C10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_1;        // 0x1C40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;          // 0x1C70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_1;         // 0x1CA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_1;       // 0x1CD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose;         // 0x1D00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;     // 0x1D30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;       // 0x1D60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose;          // 0x1D90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;          // 0x1DC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;         // 0x1DF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;            // 0x1E20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;           // 0x1E50 (size: 0x30)

}; // Size: 0x1E80

struct FAnimBlueprintGeneratedMutableData : public FAnimBlueprintMutableData
{
    float __FloatProperty;                                                            // 0x0004 (size: 0x4)
    float __FloatProperty_0;                                                          // 0x0008 (size: 0x4)
    float __FloatProperty_1;                                                          // 0x000C (size: 0x4)
    float __FloatProperty_2;                                                          // 0x0010 (size: 0x4)
    float __FloatProperty_3;                                                          // 0x0014 (size: 0x4)
    bool __BoolProperty_4;                                                            // 0x0018 (size: 0x1)
    uint8 __ByteProperty_5;                                                           // 0x0019 (size: 0x1)
    bool __BoolProperty_6;                                                            // 0x001A (size: 0x1)
    uint8 __ByteProperty_7;                                                           // 0x001B (size: 0x1)
    uint8 __ByteProperty_8;                                                           // 0x001C (size: 0x1)

}; // Size: 0x1D

class UA_Man_Riding_AnimBP_C : public UBipedRidingAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x09E0 (size: 0x8)
    FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                       // 0x09E8 (size: 0x20)
    FAnimSubsystemInstance AnimBlueprintExtension_PropertyAccess;                     // 0x0A08 (size: 0x8)
    FAnimSubsystemInstance AnimBlueprintExtension_Base;                               // 0x0A10 (size: 0x8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_10;                       // 0x0A18 (size: 0xB8)
    FAnimNode_Root AnimGraphNode_Root_7;                                              // 0x0AD0 (size: 0x20)
    FAnimNode_Root AnimGraphNode_Root_6;                                              // 0x0AF0 (size: 0x20)
    FAnimNode_LinkedAnimLayer AnimGraphNode_LinkedAnimLayer;                          // 0x0B10 (size: 0xC8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_9;                        // 0x0BD8 (size: 0xB8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_8;                        // 0x0C90 (size: 0xB8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_7;                        // 0x0D48 (size: 0xB8)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_6;                          // 0x0E00 (size: 0x80)
    FAnimNode_Root AnimGraphNode_Root_5;                                              // 0x0E80 (size: 0x20)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_6;                        // 0x0EA0 (size: 0xB8)
    FAnimNode_Root AnimGraphNode_Root_4;                                              // 0x0F58 (size: 0x20)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_5;                        // 0x0F78 (size: 0xB8)
    FAnimNode_Root AnimGraphNode_Root_3;                                              // 0x1030 (size: 0x20)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_5;                          // 0x1050 (size: 0x80)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_4;                        // 0x10D0 (size: 0xB8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_3;                        // 0x1188 (size: 0xB8)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_2;                      // 0x1240 (size: 0x70)
    FAnimNode_StateResult AnimGraphNode_StateResult_21;                               // 0x12B0 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_7;                              // 0x12D0 (size: 0xC8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_2;                        // 0x1398 (size: 0xB8)
    FAnimNode_Root AnimGraphNode_Root_2;                                              // 0x1450 (size: 0x20)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_1;                        // 0x1470 (size: 0xB8)
    FAnimNode_Root AnimGraphNode_Root_1;                                              // 0x1528 (size: 0x20)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_4;                          // 0x1548 (size: 0x80)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_17;                         // 0x15C8 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot;                                                // 0x1610 (size: 0x48)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_41;                     // 0x1658 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_40;                     // 0x1680 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_39;                     // 0x16A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_38;                     // 0x16D0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_37;                     // 0x16F8 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_15;                           // 0x1720 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_20;                               // 0x1748 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_14;                           // 0x1768 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_19;                               // 0x1790 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_16;                         // 0x17B0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_18;                               // 0x17F8 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_6;                              // 0x1818 (size: 0xC8)
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose;                          // 0x18E0 (size: 0xB8)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_36;                     // 0x1998 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_13;                           // 0x19C0 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_17;                               // 0x19E8 (size: 0x20)
    FAnimNode_StateResult AnimGraphNode_StateResult_16;                               // 0x1A08 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_5;                              // 0x1A28 (size: 0xC8)
    FAnimNode_Root AnimGraphNode_Root;                                                // 0x1AF0 (size: 0x20)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_1;                      // 0x1B10 (size: 0x70)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_7;                            // 0x1B80 (size: 0xC8)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;                        // 0x1C48 (size: 0x70)
    FAnimNode_StateResult AnimGraphNode_StateResult_15;                               // 0x1CB8 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_4;                              // 0x1CD8 (size: 0xC8)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_3;                          // 0x1DA0 (size: 0x80)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_35;                     // 0x1E20 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_34;                     // 0x1E48 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_33;                     // 0x1E70 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_32;                     // 0x1E98 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_31;                     // 0x1EC0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_30;                     // 0x1EE8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_29;                     // 0x1F10 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_28;                     // 0x1F38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_27;                     // 0x1F60 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_26;                     // 0x1F88 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_25;                     // 0x1FB0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_24;                     // 0x1FD8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_23;                     // 0x2000 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_22;                     // 0x2028 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_21;                     // 0x2050 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_20;                     // 0x2078 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_19;                     // 0x20A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_18;                     // 0x20C8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_17;                     // 0x20F0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_16;                     // 0x2118 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_15;                     // 0x2140 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_14;                     // 0x2168 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;                     // 0x2190 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_15;                         // 0x21B8 (size: 0x48)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_6;                            // 0x2200 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_12;                           // 0x22C8 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_14;                               // 0x22F0 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_14;                         // 0x2310 (size: 0x48)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_5;                            // 0x2358 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_11;                           // 0x2420 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_13;                               // 0x2448 (size: 0x20)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;                     // 0x2468 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_13;                         // 0x2490 (size: 0x48)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_4;                            // 0x24D8 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_10;                           // 0x25A0 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_12;                               // 0x25C8 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_12;                         // 0x25E8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_11;                         // 0x2630 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_10;                         // 0x2678 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;                        // 0x26C0 (size: 0x48)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_2;                        // 0x2708 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_9;                          // 0x2750 (size: 0x48)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_3;                            // 0x2798 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_9;                            // 0x2860 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_11;                               // 0x2888 (size: 0x20)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;                     // 0x28A8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;                     // 0x28D0 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_8;                          // 0x28F8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_7;                          // 0x2940 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_6;                          // 0x2988 (size: 0x48)
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;                      // 0x29D0 (size: 0x40)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_8;                            // 0x2A10 (size: 0x28)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_2;                            // 0x2A38 (size: 0xC8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;                          // 0x2B00 (size: 0x48)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_1;                        // 0x2B48 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_10;                               // 0x2B90 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;                          // 0x2BB0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;                          // 0x2BF8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;                          // 0x2C40 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;                          // 0x2C88 (size: 0x48)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend;                                  // 0x2CD0 (size: 0xC8)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_1;                            // 0x2D98 (size: 0xC8)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;                          // 0x2E60 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_7;                            // 0x2EA8 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_9;                                // 0x2ED0 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_3;                              // 0x2EF0 (size: 0xC8)
    FAnimNode_StateResult AnimGraphNode_StateResult_8;                                // 0x2FB8 (size: 0x20)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;                      // 0x2FD8 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_6;                            // 0x3000 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_7;                                // 0x3028 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_5;                            // 0x3048 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_6;                                // 0x3070 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_2;                              // 0x3090 (size: 0xC8)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_2;                          // 0x3158 (size: 0x80)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;                      // 0x31D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;                      // 0x3200 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;                      // 0x3228 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;                      // 0x3250 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;                      // 0x3278 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;                      // 0x32A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;                      // 0x32C8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;                          // 0x32F0 (size: 0x48)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive;                              // 0x3338 (size: 0xC8)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;                            // 0x3400 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_5;                                // 0x3428 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;                            // 0x3448 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_4;                                // 0x3470 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;                            // 0x3490 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_3;                                // 0x34B8 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;                            // 0x34D8 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_2;                                // 0x3500 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_1;                              // 0x3520 (size: 0xC8)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;                          // 0x35E8 (size: 0x80)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;                            // 0x3668 (size: 0x80)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;                      // 0x36E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;                        // 0x3710 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;                              // 0x3738 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_1;                                // 0x3760 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;                            // 0x3780 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult;                                  // 0x37C8 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine;                                // 0x37E8 (size: 0xC8)

    void Landing Combat(FPoseLink Default Land, FPoseLink& Landing Combat);
    void Flying Cycle Combat(FPoseLink InPose_0, FPoseLink& Flying Cycle Combat);
    void BaseBody Combat(FPoseLink BaseBody, FPoseLink N Pose, FPoseLink STR Pose, FPoseLink& BaseBody Combat);
    void UpperBody Combat(FPoseLink UpperBody, FPoseLink& UpperBody Combat);
    void PostLayering Combat(FPoseLink PostLayering In, FPoseLink& PostLayering Combat);
    void STL BaseBody Combat(FPoseLink InPose, FPoseLink STL Loco Pose, FPoseLink STL STR Pose, FPoseLink& STL BaseBody Combat);
    void IK(FPoseLink InPose, bool isTargeting, bool ShouldMove, FGameplayTag WeaponTag, FName weaponSkill, FName ItemState, double AngleBwVectors, double CharacterSpeed, double SpineCorrAlpha, EMovementState MovementState, EStance DesiredStance, double AlphaArmR, double AlphaArmL, double ArmR_Corr, double ArmL_Corr, bool isInDialog, bool IsTurning, int32 LOD, bool HasWeapon, bool IsInSecondPhase, double SlopeAngle, bool IsOnSlope, bool IsStopping, bool isPlayer, bool IsAttacking, bool IsDrawingWeapon, FPoseLink& IK);
    void AnimGraph(FPoseLink& AnimGraph);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_5B45EE964EC8E732E15ABEBF3FAB1F08();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_F7FC53DB4791661413F8D1A7D860CA9C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_38C7865D4233460C0BAD29BD2A9917C7();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_D61DD46246BB6F502706BC86C210B028();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_F923A6D74BCA6FEFFFF0DFA98C1691C8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_A38527B743A019D74FEB73BFBB530143();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_108A959C43ED1660E03359B8A30FB45F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_D649665347A96E157611F7AE22D38D28();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_023371B84254EE672965BFBDB8E8A253();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TwoWayBlend_24BFB3F146D23353BD2455B00BC23177();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_197FCEAA4CA2380B6C62BC96311C1C07();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_BlendListByBool_C6410ABC41BD764A60EA8E973A6C451B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_B00A18584F745B2DBD0213B319143EA5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_E8D1AD4C45EF7D6304F228A42911CCB5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_ADC8DA4344CD6D0F0E7B12A609B15B21();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_620F6AA842BFB4ACF250D1B17C6CB88A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_135FEEB842C47D03F54A7385717A5AD4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_9EDFE9324A6568A62AE0ADA2DAC99B6A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_F10B0CE34A22466357712BAE3C3C8ED4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_C1751C174A6FCBE7F82DFD99EECF2942();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_59FA1C3E4CF5DF7F5CEB6FBCEDFDEA62();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_1312ADD849C278655E7A69B42872D589();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_A028620441CB5EEBDB5D78A487692F15();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_8817219B4B5B1A4B0B4114984D0ABCED();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_E51D8CB0481C74FCC54F18B301EDE1EC();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_B2D8AD9F4B5106EF0269019670851E1E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_8351A3E248FDC57B271CB7ACE8D1F1C5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_7E81381B49AAEF052119028AA9DE79C4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_21CC1DC0432E36A196F7D596F707C041();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_662531D04937F8A7CFFD45969F04F3BE();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_D95FE6F044B2BF595A16C7B023EDE879();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_533701ED4509F51300464784EEAB6D28();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_E9D746954056D7CE0782CF949DB8D9F5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_819BA6704AED298A4D6FBC8B3DBF7DA6();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_A6CDB7D842FD5D9DDCFA04AAF217E1EF();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_A_Man_Riding_AnimBP_AnimGraphNode_TransitionResult_BF3D1FFE4D2B1E2F7BDD58B5C2E8305B();
    void AnimNotify_StopSprint();
    void AnimNotify_StopMoving();
    void AnimNotify_StopTransition();
    void AnimNotify_OnMoving();
    void AnimNotify_SprintToStop();
    void ExecuteUbergraph_A_Man_Riding_AnimBP(int32 EntryPoint);
}; // Size: 0x38B0

#endif
