enum class BFGInstancedSkeletalMeshInterpolationAction_OnFinish {
    INTERPOLATION_ACTION_NONE = 0,
    INTERPOLATION_ACTION_LOOP = 1,
    INTERPOLATION_ACTION_HIDE = 2,
    INTERPOLATION_ACTION_DESTROY = 3,
    INTERPOLATION_ACTION_COUNT = 4,
    INTERPOLATION_ACTION_MAX = 5,
};

