#ifndef UE4SS_SDK_NinjaLiveComponent_HPP
#define UE4SS_SDK_NinjaLiveComponent_HPP

class UNinjaLiveComponent_C : public UNativeNinjaLiveComponent
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x00A0 (size: 0x8)
    bool ComponentActivatedByPawnProximity;                                           // 0x00A8 (size: 0x1)
    bool DisableComponent;                                                            // 0x00A9 (size: 0x1)
    bool BeginPlaySupressed;                                                          // 0x00AA (size: 0x1)
    bool InitDone;                                                                    // 0x00AB (size: 0x1)
    bool MaterialInstacesDone;                                                        // 0x00AC (size: 0x1)
    bool AutoConnectToMemoryPool-IF-Found;                                            // 0x00AD (size: 0x1)
    bool MemPoolManagerDetected;                                                      // 0x00AE (size: 0x1)
    bool PoolManagerOverridesLocalSettings;                                           // 0x00AF (size: 0x1)
    int32 ResolutionX;                                                                // 0x00B0 (size: 0x4)
    int32 ResolutionY;                                                                // 0x00B4 (size: 0x4)
    FString PreferredTraceChannelName;                                                // 0x00B8 (size: 0x10)
    TEnumAsByte<ETraceTypeQuery> TraceChannel;                                        // 0x00C8 (size: 0x1)
    TEnumAsByte<ECollisionChannel> CollisionChannel;                                  // 0x00C9 (size: 0x1)
    bool TraceChannelsSet;                                                            // 0x00CA (size: 0x1)
    TEnumAsByte<SimPrecision_Enum::Type> SimPrecision;                                // 0x00CB (size: 0x1)
    bool UsePressureSolver1_(DefaultIs2);                                             // 0x00CC (size: 0x1)
    int32 PressureSolver1_MaxIterations;                                              // 0x00D0 (size: 0x4)
    int32 PressureSolver2_MaxIterations;                                              // 0x00D4 (size: 0x4)
    double PressureSolver2_KernelReduction;                                           // 0x00D8 (size: 0x8)
    int32 MaxSamplingFPS;                                                             // 0x00E0 (size: 0x4)
    int32 MinSamplingFPS;                                                             // 0x00E4 (size: 0x4)
    bool HalfResPressureAndDivergenceBuffers;                                         // 0x00E8 (size: 0x1)
    bool ShowDebugMessages-TraceChannels;                                             // 0x00E9 (size: 0x1)
    bool ShowDebugMessages-MemoryManagement;                                          // 0x00EA (size: 0x1)
    bool ShowDebugMessages-CollisionAndTracing;                                       // 0x00EB (size: 0x1)
    bool ShowDebugMessages-LODInitial;                                                // 0x00EC (size: 0x1)
    bool ShowDebugMessages-LODRuntime;                                                // 0x00ED (size: 0x1)
    bool ShowDebugMessages-InterfaceControl;                                          // 0x00EE (size: 0x1)
    bool ShowDebugMessages-RenderTargetExport;                                        // 0x00EF (size: 0x1)
    bool ShowDebugMessages-NumberOfTrackedObjects;                                    // 0x00F0 (size: 0x1)
    bool ShowWarning-NumberOfBonesToTrack;                                            // 0x00F1 (size: 0x1)
    bool VisualizeCustomTraceSource;                                                  // 0x00F2 (size: 0x1)
    bool SaveDebugMessagesToDefaultLog;                                               // 0x00F3 (size: 0x1)
    double DebugMessagesLifetime;                                                     // 0x00F8 (size: 0x8)
    class UStaticMeshComponent* TraceMeshComponent;                                   // 0x0100 (size: 0x8)
    int32 SamplingFPS;                                                                // 0x0108 (size: 0x4)
    double TickRateCustom;                                                            // 0x0110 (size: 0x8)
    bool LOD1-ReduceSimQuality;                                                       // 0x0118 (size: 0x1)
    bool LOD2-ReduceSamplingFPS;                                                      // 0x0119 (size: 0x1)
    double LOD-NearBound;                                                             // 0x0120 (size: 0x8)
    double LOD-FarBound;                                                              // 0x0128 (size: 0x8)
    int32 LOD-Steps;                                                                  // 0x0130 (size: 0x4)
    double LOD-StepRange;                                                             // 0x0138 (size: 0x8)
    TArray<double> LOD-StepsArray;                                                    // 0x0140 (size: 0x10)
    int32 SimPrecisionIndex;                                                          // 0x0150 (size: 0x4)
    double MemConsumption;                                                            // 0x0158 (size: 0x8)
    int32 MapLengthTmp;                                                               // 0x0160 (size: 0x4)
    class UMaterialInstance* InactiveGrayMaterial;                                    // 0x0168 (size: 0x8)
    FNinjaLiveComponent_CComponentRePlayEvent ComponentRePlayEvent;                   // 0x0170 (size: 0x10)
    void ComponentRePlayEvent();
    FNinjaLiveComponent_CComponentBroadcastMemConsumption ComponentBroadcastMemConsumption; // 0x0180 (size: 0x10)
    void ComponentBroadcastMemConsumption(class UObject* Consumer, double MemConsumption, bool TakenOrReturned);
    bool PawnInsideActivationBounds;                                                  // 0x0190 (size: 0x1)
    class UDataTable* LoadedDataTable;                                                // 0x0198 (size: 0x8)
    FString LoadedDataTablePath;                                                      // 0x01A0 (size: 0x10)
    TMap<FString, double> PresetMap;                                                  // 0x01B0 (size: 0x50)
    FString ActualPreset;                                                             // 0x0200 (size: 0x10)
    class UDataTable* DefaultPreset;                                                  // 0x0210 (size: 0x8)
    TArray<FName> PresetSearchPaths;                                                  // 0x0218 (size: 0x10)
    FName PresetNameFilterCriteria;                                                   // 0x0228 (size: 0x8)
    bool TraceMeshInvisible;                                                          // 0x0230 (size: 0x1)
    int32 OutputMaterialSelected;                                                     // 0x0234 (size: 0x4)
    TArray<class UMaterialInterface*> OutputMaterials;                                // 0x0238 (size: 0x10)
    bool ForceAutoLoadPreset;                                                         // 0x0248 (size: 0x1)
    TArray<FString> RenderTargetsList;                                                // 0x0250 (size: 0x10)
    TMap<class FString, class UTextureRenderTarget2D*> RenderTargetsMap;              // 0x0260 (size: 0x50)
    class UMaterialInstanceDynamic* MI_Advection;                                     // 0x02B0 (size: 0x8)
    class UMaterialInstanceDynamic* MI_Divergence;                                    // 0x02B8 (size: 0x8)
    class UMaterialInstanceDynamic* MI_PressureCycle1;                                // 0x02C0 (size: 0x8)
    class UMaterialInstanceDynamic* MI_PressureCycle2;                                // 0x02C8 (size: 0x8)
    double VeloStrength;                                                              // 0x02D0 (size: 0x8)
    double VeloOffsetX;                                                               // 0x02D8 (size: 0x8)
    double VeloOffsetY;                                                               // 0x02E0 (size: 0x8)
    double VeloRotate;                                                                // 0x02E8 (size: 0x8)
    double VeloAmpNoise;                                                              // 0x02F0 (size: 0x8)
    double VeloDirNoise;                                                              // 0x02F8 (size: 0x8)
    double Speed;                                                                     // 0x0300 (size: 0x8)
    FName Apply1stOutMatToActorsWithTag;                                              // 0x0308 (size: 0x8)
    FName Apply1stOutMatToComponentsWithTag;                                          // 0x0310 (size: 0x8)
    FName FeedTaggedActorNiagaraComponent;                                            // 0x0318 (size: 0x8)
    bool Make1stOutputAvailableFor2ndOutput;                                          // 0x0320 (size: 0x1)
    bool Make1stOutputAvailableForNiagara;                                            // 0x0321 (size: 0x1)
    bool MakePressureAvailableForNiagara;                                             // 0x0322 (size: 0x1)
    int32 SecondaryOutputMaterialSelected;                                            // 0x0324 (size: 0x4)
    TArray<class UMaterialInterface*> SecondaryOutputMaterials;                       // 0x0328 (size: 0x10)
    FName Apply2ndOutMatToActorsWithTag;                                              // 0x0338 (size: 0x8)
    FName Apply2ndOutMatToComponentsWithTag;                                          // 0x0340 (size: 0x8)
    int32 TertiaryOutputMaterialSelected;                                             // 0x0348 (size: 0x4)
    TArray<class UMaterialInterface*> TertiaryOutputMaterials;                        // 0x0350 (size: 0x10)
    FName Apply3rdOutMatToActorsWithTag;                                              // 0x0360 (size: 0x8)
    FName Apply3rdOutMatToComponentsWithTag;                                          // 0x0368 (size: 0x8)
    bool UseRenderTargetAsInput;                                                      // 0x0370 (size: 0x1)
    class UTextureRenderTarget* InputRenderTarget;                                    // 0x0378 (size: 0x8)
    bool RGB-InputMaterial;                                                           // 0x0380 (size: 0x1)
    bool InputMaterialClamp;                                                          // 0x0381 (size: 0x1)
    int32 InputMaterialSelected;                                                      // 0x0384 (size: 0x4)
    TArray<class UMaterialInterface*> InputMaterials;                                 // 0x0388 (size: 0x10)
    bool SimAreaClamp;                                                                // 0x0398 (size: 0x1)
    bool ShowMouseCursor;                                                             // 0x0399 (size: 0x1)
    double Divergence;                                                                // 0x03A0 (size: 0x8)
    double InputFeedback;                                                             // 0x03A8 (size: 0x8)
    double FlowFeedback;                                                              // 0x03B0 (size: 0x8)
    double VeloFromSimAreaMotion;                                                     // 0x03B8 (size: 0x8)
    double OffsetFromSimAreaMotion;                                                   // 0x03C0 (size: 0x8)
    double VeloFromBrushMotion;                                                       // 0x03C8 (size: 0x8)
    double BrushSize;                                                                 // 0x03D0 (size: 0x8)
    double BrushStrength;                                                             // 0x03D8 (size: 0x8)
    double BrushStrengthTemp1;                                                        // 0x03E0 (size: 0x8)
    bool EraserMode;                                                                  // 0x03E8 (size: 0x1)
    double BrushHardness;                                                             // 0x03F0 (size: 0x8)
    FString ParticleTemplate;                                                         // 0x03F8 (size: 0x10)
    FString DensityTemplate;                                                          // 0x0408 (size: 0x10)
    FString VelocityTemplate;                                                         // 0x0418 (size: 0x10)
    FString MetaData;                                                                 // 0x0428 (size: 0x10)
    double BrushPuncture;                                                             // 0x0438 (size: 0x8)
    class UMaterialInstanceDynamic* MI_CollisionPainterDot;                           // 0x0440 (size: 0x8)
    class UMaterialInstanceDynamic* MI_CollisionPainterLine;                          // 0x0448 (size: 0x8)
    class UMaterialInstanceDynamic* MI_CollisionPainterOffset;                        // 0x0450 (size: 0x8)
    class UMaterialInstanceDynamic* MI_CompositeAndGradient;                          // 0x0458 (size: 0x8)
    class UMaterialInstanceDynamic* MI_Output;                                        // 0x0460 (size: 0x8)
    class UMaterialInstanceDynamic* MI_SecondaryOutput;                               // 0x0468 (size: 0x8)
    class UMaterialInstanceDynamic* MI_TertiaryOutput;                                // 0x0470 (size: 0x8)
    class UMaterialInstanceDynamic* MI_Null;                                          // 0x0478 (size: 0x8)
    class UMaterialInterface* NullMaterial;                                           // 0x0480 (size: 0x8)
    FName NullName;                                                                   // 0x0488 (size: 0x8)
    FString NullString;                                                               // 0x0490 (size: 0x10)
    class UTexture2D* VelocityInput;                                                  // 0x04A0 (size: 0x8)
    class UTexture2D* DensityInput;                                                   // 0x04A8 (size: 0x8)
    bool FlipRenderTargetsForMobile;                                                  // 0x04B0 (size: 0x1)
    bool SelfService-IF-PoolEmpty;                                                    // 0x04B1 (size: 0x1)
    class UBoxComponent* ActivationVolume;                                            // 0x04B8 (size: 0x8)
    bool AutonomousMode;                                                              // 0x04C0 (size: 0x1)
    bool AbsPathForVelocityTemplate;                                                  // 0x04C1 (size: 0x1)
    bool AbsPathForDensityTemplate;                                                   // 0x04C2 (size: 0x1)
    TMap<int32, UPrimitiveComponent*> SkeletalMesh-TempArray-Pairs;                   // 0x04C8 (size: 0x50)
    TArray<class UPrimitiveComponent*> OverlappingComponents;                         // 0x0518 (size: 0x10)
    TArray<class USkeletalMeshComponent*> ContinuousInteractionSkeletalComponent;     // 0x0528 (size: 0x10)
    TArray<bool> ListOfAvailableTempArrays;                                           // 0x0538 (size: 0x10)
    class UPrimitiveComponent* OverlappingSkeletalMesh;                               // 0x0548 (size: 0x8)
    FName OverlappingBone;                                                            // 0x0550 (size: 0x8)
    FVector Position1_3D;                                                             // 0x0558 (size: 0x18)
    FVector LastPosition1_3D;                                                         // 0x0570 (size: 0x18)
    double TraceMeshSizeCoeff;                                                        // 0x0588 (size: 0x8)
    double OverlappingMeshSizeCoeff;                                                  // 0x0590 (size: 0x8)
    class UPrimitiveComponent* OverlappingComponent;                                  // 0x0598 (size: 0x8)
    int32 TouchLookupIndex;                                                           // 0x05A0 (size: 0x4)
    TArray<FLinearColor> LastPosition3_2D;                                            // 0x05A8 (size: 0x10)
    FLinearColor LastPosition2_2D;                                                    // 0x05B8 (size: 0x10)
    bool MousePass;                                                                   // 0x05C8 (size: 0x1)
    FLinearColor Position2_2D;                                                        // 0x05CC (size: 0x10)
    TArray<FLinearColor> Position3_2D;                                                // 0x05E0 (size: 0x10)
    int32 PosDataType;                                                                // 0x05F0 (size: 0x4)
    bool ShowVelocityDebugCone;                                                       // 0x05F4 (size: 0x1)
    bool IgnoreInterfaceCommands;                                                     // 0x05F5 (size: 0x1)
    bool DisableAndNotTickBlock;                                                      // 0x05F6 (size: 0x1)
    double InputFeedbackInterface;                                                    // 0x05F8 (size: 0x8)
    double BrushStrengthTemp2;                                                        // 0x0600 (size: 0x8)
    bool TickBlocker;                                                                 // 0x0608 (size: 0x1)
    int32 FluidSolver1Iterations;                                                     // 0x060C (size: 0x4)
    TArray<class AActor*> NinjaLIVETraceExclude;                                      // 0x0610 (size: 0x10)
    double DeltaSeconds;                                                              // 0x0620 (size: 0x8)
    bool UseUnrealNativeEventTick;                                                    // 0x0628 (size: 0x1)
    bool SingleInput;                                                                 // 0x0629 (size: 0x1)
    bool Touch;                                                                       // 0x062A (size: 0x1)
    double LOD-CheckFrequency;                                                        // 0x0630 (size: 0x8)
    bool PauseSimWhenNotVisible;                                                      // 0x0638 (size: 0x1)
    double WaitBeforePause;                                                           // 0x0640 (size: 0x8)
    bool MousePressed;                                                                // 0x0648 (size: 0x1)
    bool ContinuousInteractionWithOwnerActor;                                         // 0x0649 (size: 0x1)
    TArray<TEnumAsByte<EObjectTypeQuery>> ContinuousInteractionInclusiveObjType;      // 0x0650 (size: 0x10)
    TArray<FName> ContinuousInteractionComponentNamesExact;                           // 0x0660 (size: 0x10)
    TArray<FName> ContinuousInteractionBoneNamesExact;                                // 0x0670 (size: 0x10)
    TArray<FName> ContinuousInteractionBoneNamesExactTemp;                            // 0x0680 (size: 0x10)
    TArray<FName> ContinuousInteractionBoneNamesExactTemp2;                           // 0x0690 (size: 0x10)
    bool UsePAINTER_V2_ToTrackObjects;                                                // 0x06A0 (size: 0x1)
    bool PV2_Connect_TrackpointsWithLines;                                            // 0x06A1 (size: 0x1)
    bool PV2_Interpolation;                                                           // 0x06A2 (size: 0x1)
    bool PV2_GenerateVelocity;                                                        // 0x06A3 (size: 0x1)
    double PV2_LineDrawingFailCooldownTime;                                           // 0x06A8 (size: 0x8)
    float PV2_StopLineDrawingAboveThisVelocity;                                       // 0x06B0 (size: 0x4)
    bool SimplePainterMode;                                                           // 0x06B4 (size: 0x1)
    bool CameraFacingTraceMesh;                                                       // 0x06B5 (size: 0x1)
    bool CameraFacing_LockY-Axis;                                                     // 0x06B6 (size: 0x1)
    bool UseCustomTraceSource;                                                        // 0x06B7 (size: 0x1)
    FVector CustomTraceSourcePosition;                                                // 0x06B8 (size: 0x18)
    TEnumAsByte<QuantizerMode::Type> TraceMeshMovingInWorldSpace;                     // 0x06D0 (size: 0x1)
    TEnumAsByte<QuantizerAxisIgnore::Type> MovementNotQuantizedToStepsOnAxis;         // 0x06D1 (size: 0x1)
    TEnumAsByte<QuantizerAxisIgnore::Type> MovementIsLockedOnThisAxis;                // 0x06D2 (size: 0x1)
    bool ForceTraceMeshToCustomVerticalPos;                                           // 0x06D3 (size: 0x1)
    double ForceTraceMeshVerticalPosition;                                            // 0x06D8 (size: 0x8)
    bool InteractionVolumeIsPresent;                                                  // 0x06E0 (size: 0x1)
    int32 QuantizerStepSize;                                                          // 0x06E4 (size: 0x4)
    FLinearColor Position1_2D;                                                        // 0x06E8 (size: 0x10)
    double TimeSinceLastClick;                                                        // 0x06F8 (size: 0x8)
    bool Position1_3D_Static;                                                         // 0x0700 (size: 0x1)
    double TimeSinceLastCollision;                                                    // 0x0708 (size: 0x8)
    double TimeCounter;                                                               // 0x0710 (size: 0x8)
    bool Overlap1;                                                                    // 0x0718 (size: 0x1)
    FNinjaLiveComponent_CComponentShutdownEvent ComponentShutdownEvent;               // 0x0720 (size: 0x10)
    void ComponentShutdownEvent();
    bool OverlapBasedInteraction;                                                     // 0x0730 (size: 0x1)
    TEnumAsByte<UserInput_Enum::Type> UserInputBasedInteraction;                      // 0x0731 (size: 0x1)
    bool BrushScaledInverselyByTraceMeshSize;                                         // 0x0732 (size: 0x1)
    bool BrushScaledByInteractingObjSize;                                             // 0x0733 (size: 0x1)
    bool UseObjBoundsInsteadOfSize;                                                   // 0x0734 (size: 0x1)
    double GlobalBrushScale;                                                          // 0x0738 (size: 0x8)
    double UserInputBrushScale;                                                       // 0x0740 (size: 0x8)
    double PrimitiveObjBrushScale;                                                    // 0x0748 (size: 0x8)
    double SkeletalMeshBrushScale;                                                    // 0x0750 (size: 0x8)
    int32 TraceMeshQueryCounter;                                                      // 0x0758 (size: 0x4)
    double LimitUnrealNativeEventTick;                                                // 0x0760 (size: 0x8)
    bool GlobalVeloTempCondition;                                                     // 0x0768 (size: 0x1)
    FVector TracePositionTemp;                                                        // 0x0770 (size: 0x18)
    FVector LastTracePositionTemp;                                                    // 0x0788 (size: 0x18)
    double SimEdgeBouncyness;                                                         // 0x07A0 (size: 0x8)
    double FadeDensityAtSimEdge;                                                      // 0x07A8 (size: 0x8)
    double EdgeMaskWidth;                                                             // 0x07B0 (size: 0x8)
    double VeloDirNoiseSize;                                                          // 0x07B8 (size: 0x8)
    double VeloDirNoiseSpeed;                                                         // 0x07C0 (size: 0x8)
    bool UseInputMaterials;                                                           // 0x07C8 (size: 0x1)
    double DensityTxtScale;                                                           // 0x07D0 (size: 0x8)
    double DensityTxtOffsetX;                                                         // 0x07D8 (size: 0x8)
    double DensityTxtOffsetY;                                                         // 0x07E0 (size: 0x8)
    double BrushNoise;                                                                // 0x07E8 (size: 0x8)
    bool BrushNoiseInWorldSpace;                                                      // 0x07F0 (size: 0x1)
    double BrushDensityNoiseScale;                                                    // 0x07F8 (size: 0x8)
    double BrushDensityNoiseFreq;                                                     // 0x0800 (size: 0x8)
    double BrushVelocityNoiseScale;                                                   // 0x0808 (size: 0x8)
    double BrushVelocityNoiseFreq;                                                    // 0x0810 (size: 0x8)
    FRotator TraceMeshInitialRotation;                                                // 0x0818 (size: 0x18)
    bool EnableRayMarching;                                                           // 0x0830 (size: 0x1)
    class AActor* LightDirectionProvider;                                             // 0x0838 (size: 0x8)
    bool LightDirectionSourceIsRotation_NOT_Pos;                                      // 0x0840 (size: 0x1)
    bool DistanceBasedLightAttenuation;                                               // 0x0841 (size: 0x1)
    double AttenuationPower;                                                          // 0x0848 (size: 0x8)
    double PointLightMovementMultiplier;                                              // 0x0850 (size: 0x8)
    bool TwoSidedShading;                                                             // 0x0858 (size: 0x1)
    double TwoSideBlendPow;                                                           // 0x0860 (size: 0x8)
    double Facing;                                                                    // 0x0868 (size: 0x8)
    FVector OffsetLightVector;                                                        // 0x0870 (size: 0x18)
    bool ForceManualSunPosition;                                                      // 0x0888 (size: 0x1)
    double SunLatitude;                                                               // 0x0890 (size: 0x8)
    double SunLongitude;                                                              // 0x0898 (size: 0x8)
    double SunHeight;                                                                 // 0x08A0 (size: 0x8)
    bool ShowLightDirectionVector_(Yellow);                                           // 0x08A8 (size: 0x1)
    bool ShowNiagaraSysUpvector_(Red);                                                // 0x08A9 (size: 0x1)
    bool ShowFacingPlane;                                                             // 0x08AA (size: 0x1)
    bool PrintFacing;                                                                 // 0x08AB (size: 0x1)
    double VeloInputTile;                                                             // 0x08B0 (size: 0x8)
    double VeloInputOffsetSpeed;                                                      // 0x08B8 (size: 0x8)
    double DensityTxtMult;                                                            // 0x08C0 (size: 0x8)
    double DensityInputNoiseAmp;                                                      // 0x08C8 (size: 0x8)
    double DensityInputNoiseOffset;                                                   // 0x08D0 (size: 0x8)
    double DensityInputNoiseTile;                                                     // 0x08D8 (size: 0x8)
    FString InternalParameterIdentifier;                                              // 0x08E0 (size: 0x10)
    class UMaterialParameterCollection* SetInternalParamsToMaterialParamCollection;   // 0x08F0 (size: 0x8)
    bool DrawInternalRenderTargetToExternal;                                          // 0x08F8 (size: 0x1)
    TArray<TEnumAsByte<RenderTargetList::Type>> InternalRenderTargetsToExport;        // 0x0900 (size: 0x10)
    TArray<class UTextureRenderTarget2D*> ExternalRenderTargets;                      // 0x0910 (size: 0x10)
    class UTexture* CollisionMask;                                                    // 0x0920 (size: 0x8)
    bool CollisionMaskIsNonDefault;                                                   // 0x0928 (size: 0x1)
    class ASceneCapture2D* InputSceneCaptureCamera;                                   // 0x0930 (size: 0x8)
    class UMediaPlayer* InputMediaPlayer;                                             // 0x0938 (size: 0x8)
    class UMediaTexture* MediaTexture;                                                // 0x0940 (size: 0x8)
    class UFileMediaSource* InputMediaSource;                                         // 0x0948 (size: 0x8)
    double InputMediaLoopLength;                                                      // 0x0950 (size: 0x8)
    bool RandomizeNoiseOffsets;                                                       // 0x0958 (size: 0x1)
    int32 OverlapCounter;                                                             // 0x095C (size: 0x4)
    bool RandomizeDensityTextureOffset;                                               // 0x0960 (size: 0x1)
    class UTexture2D* OverwritePresetDensityInput;                                    // 0x0968 (size: 0x8)
    class UTexture2D* OverwritePresetVelocityInput;                                   // 0x0970 (size: 0x8)
    double BrushRnd;                                                                  // 0x0978 (size: 0x8)
    double SimSpeedAdjustmentLatency;                                                 // 0x0980 (size: 0x8)
    double SpeedTemp;                                                                 // 0x0988 (size: 0x8)
    bool StopUsingPainterCanvasWhenIdle;                                              // 0x0990 (size: 0x1)
    int32 Experimental_PSolver2KernelIndexOffset;                                     // 0x0994 (size: 0x4)
    double Experimental_PressureFeedback;                                             // 0x0998 (size: 0x8)
    bool TraceMeshIsAlsoInteractionVolume;                                            // 0x09A0 (size: 0x1)
    TArray<FName> TempArray0;                                                         // 0x09A8 (size: 0x10)
    TArray<FName> TempArray1;                                                         // 0x09B8 (size: 0x10)
    TArray<FName> TempArray2;                                                         // 0x09C8 (size: 0x10)
    TArray<FName> TempArray3;                                                         // 0x09D8 (size: 0x10)
    TArray<FName> TempArray4;                                                         // 0x09E8 (size: 0x10)
    double DampenBrushBelowThisVelocity;                                              // 0x09F8 (size: 0x8)
    bool DampenIgnoresStaticMeshes;                                                   // 0x0A00 (size: 0x1)
    double DampenBrushFactor;                                                         // 0x0A08 (size: 0x8)
    double BrushVelocityPow;                                                          // 0x0A10 (size: 0x8)
    double BrushVelocityClamp;                                                        // 0x0A18 (size: 0x8)
    double SimAreaMotionEffectsBrushPuncture;                                         // 0x0A20 (size: 0x8)
    int32 LODLevel;                                                                   // 0x0A28 (size: 0x4)
    bool AllowAbsoluteBlackDensity;                                                   // 0x0A2C (size: 0x1)
    FVector TraceMeshPos;                                                             // 0x0A30 (size: 0x18)
    FVector TraceMeshLastPos;                                                         // 0x0A48 (size: 0x18)
    double PressureEdgeMasking;                                                       // 0x0A60 (size: 0x8)
    TArray<class UMaterialInterface*> CoreSimMaterials;                               // 0x0A68 (size: 0x10)
    FVector TraceMeshDeltaPos;                                                        // 0x0A78 (size: 0x18)
    FVector NullVector;                                                               // 0x0A90 (size: 0x18)
    FVector TraceMeshPosInitialLocal;                                                 // 0x0AA8 (size: 0x18)
    FVector TraceMeshPosInitialFractionalPart;                                        // 0x0AC0 (size: 0x18)
    FVector TraceMeshPosInitialWorld;                                                 // 0x0AD8 (size: 0x18)
    FVector TraceMeshParentPos;                                                       // 0x0AF0 (size: 0x18)
    FVector TraceMeshParentLastPos;                                                   // 0x0B08 (size: 0x18)
    bool SecondaryMaterialsPresent;                                                   // 0x0B20 (size: 0x1)
    bool SingleTargetMode_LEGACY;                                                     // 0x0B21 (size: 0x1)
    TEnumAsByte<SingleObjectType_Enum::Type> SingleTargetType_LEGACY;                 // 0x0B22 (size: 0x1)
    int32 SingleTargetModeSkeletalMeshIndex_LEGACY;                                   // 0x0B24 (size: 0x4)
    bool SingleTargetModeSetSimSpeed_LEGACY;                                          // 0x0B28 (size: 0x1)
    double SingleTargetMode_SpeedInfluenceFactor_LEGACY;                              // 0x0B30 (size: 0x8)
    bool EnablePainterDoubleBuffering;                                                // 0x0B38 (size: 0x1)
    bool UseLegacyCameraFacing;                                                       // 0x0B39 (size: 0x1)
    int32 TraceMeshTranslucentSortPrio;                                               // 0x0B3C (size: 0x4)
    class UBoxComponent* InteractionVolume;                                           // 0x0B40 (size: 0x8)
    bool NiagaraSystemsPresent;                                                       // 0x0B48 (size: 0x1)
    TArray<class UNiagaraComponent*> NiagaraSystemsToDrive;                           // 0x0B50 (size: 0x10)
    double Exp_PressureFeedbackComponent;                                             // 0x0B60 (size: 0x8)
    double Exp_DivergenceFeedbackComponent;                                           // 0x0B68 (size: 0x8)
    bool Force8bitSimplePainterBuffers;                                               // 0x0B70 (size: 0x1)
    bool Force8bitOutputBuffer;                                                       // 0x0B71 (size: 0x1)
    class UPrimitiveComponent* SingleTarget;                                          // 0x0B78 (size: 0x8)
    bool UE5EAFLAG;                                                                   // 0x0B80 (size: 0x1)
    bool Force2xResolutionOutputBuffer;                                               // 0x0B81 (size: 0x1)
    bool ForceMaxSamplingFPS-ToNiagara;                                               // 0x0B82 (size: 0x1)
    bool MaterialCollectionPresent;                                                   // 0x0B83 (size: 0x1)
    FNinjaLiveComponent_CWorldSpaceOffset WorldSpaceOffset;                           // 0x0B88 (size: 0x10)
    void WorldSpaceOffset(FVector TraceMeshPos);
    bool TertiaryMaterialsPresent;                                                    // 0x0B98 (size: 0x1)
    bool SupressUE51TextureSmearing;                                                  // 0x0B99 (size: 0x1)
    class ANinjaLive_MemoryPoolManager_C* Memory Pool Manager;                        // 0x0BA0 (size: 0x8)
    class UNiagaraComponent* NiagaraBasedPainter;                                     // 0x0BA8 (size: 0x8)
    TArray<FVector2D> PositionArray;                                                  // 0x0BB0 (size: 0x10)
    TArray<FVector2D> LastPositionArray;                                              // 0x0BC0 (size: 0x10)
    TArray<FLinearColor> VelocityArray;                                               // 0x0BD0 (size: 0x10)
    TArray<class UNiagaraSystem*> CoreNiagaraSystems;                                 // 0x0BE0 (size: 0x10)
    TArray<double> BrushSizeArray;                                                    // 0x0BF0 (size: 0x10)
    float AdjustPainter_V2_BrushStrength;                                             // 0x0C00 (size: 0x4)
    int32 OverlapCounterAtomic;                                                       // 0x0C04 (size: 0x4)
    TArray<class UPrimitiveComponent*> PrimitivesArray;                               // 0x0C08 (size: 0x10)
    TArray<class UPrimitiveComponent*> LastPrimitivesArray;                           // 0x0C18 (size: 0x10)
    bool UserBonenamesArrayInitiallyEmpty;                                            // 0x0C28 (size: 0x1)
    TArray<class UPrimitiveComponent*> SKmeshesArray;                                 // 0x0C30 (size: 0x10)
    TArray<class UPrimitiveComponent*> LastSKmeshesArray;                             // 0x0C40 (size: 0x10)
    float AdjustPainter_V2_EdgeMask;                                                  // 0x0C50 (size: 0x4)
    bool HitValid;                                                                    // 0x0C54 (size: 0x1)
    float AdjustPainter_V2_BrushVeloNoise;                                            // 0x0C58 (size: 0x4)
    class UTexture* Painter_V2_BrushVeloNoiseTexture;                                 // 0x0C60 (size: 0x8)
    double NiagaraVariableSetSafetyDelay;                                             // 0x0C68 (size: 0x8)
    bool LWCsupport;                                                                  // 0x0C70 (size: 0x1)
    bool LWCAvoidNiagaraWarnings;                                                     // 0x0C71 (size: 0x1)
    int32 GothicIndex;                                                                // 0x0C74 (size: 0x4)
    double Brush2Coeff;                                                               // 0x0C78 (size: 0x8)
    double FPS_Speed;                                                                 // 0x0C80 (size: 0x8)
    double KernelMult;                                                                // 0x0C88 (size: 0x8)
    bool IsBudgeted;                                                                  // 0x0C90 (size: 0x1)
    int32 Resolution_X_XSS;                                                           // 0x0C94 (size: 0x4)
    int32 Resolution_Y_XSS;                                                           // 0x0C98 (size: 0x4)
    int32 Initial Res X;                                                              // 0x0C9C (size: 0x4)
    int32 Initial Res Y;                                                              // 0x0CA0 (size: 0x4)
    int32 Scalability Factor;                                                         // 0x0CA4 (size: 0x4)
    TMap<class UTextureRenderTarget2D*, class FIntVector> OriginalSizes;              // 0x0CA8 (size: 0x50)

    void UpdateResolution();
    void ResizeByFactor(int32 Factor);
    void ResetTempArrays();
    void PresetSave(FString SelectedProject, FString SelectedPreset, bool OverWriteOrNot);
    void PresetSelectionChanged(FString SelectedPreset, bool ForceAutoLoadPreset);
    void SelChanged(FString SelectedMenuItem, FString SelectedActorName);
    void ReceiveEndPlay(TEnumAsByte<EEndPlayReason::Type> EndPlayReason);
    void Reinitialize Render Targets();
    void ComponentRePlayEvent2();
    void Custom Tick(float DeltaTime);
    void Unregister Tick();
    void Register Tick();
    void Shutdown();
    void ReceiveBeginPlay();
    void LiveFluidParams(double BrushSize);
    void LiveActivation(FName ParamName, double FadeTimeOfBrush, double FadeTimeOfCanvas);
    void Replay();
    void ExecuteUbergraph_NinjaLiveComponent(int32 EntryPoint);
    void WorldSpaceOffset__DelegateSignature(FVector TraceMeshPos);
    void ComponentShutdownEvent__DelegateSignature();
    void ComponentBroadcastMemConsumption__DelegateSignature(class UObject* Consumer, double MemConsumption, bool TakenOrReturned);
    void ComponentRePlayEvent__DelegateSignature();
}; // Size: 0xCF8

#endif
